#index:
#    path: /
#    controller: App\Controller\DefaultController::index
task_new:
  path: /tasks/new
  controller: App\Controller\TaskController::taskNew

task_show:
  path: /tasks/{id}
  controller: App\Controller\TaskController::show